name: Erlang rebar CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        version: [27, 26, 25, 24, 23, 22, 21, 20]
        rebar: [rebar, rebar3]
    container:
      image: erlang:${{ matrix.version }}
    steps:
    - uses: actions/checkout@v3
    - name: Compile
      run: ${{ matrix.rebar }} compile
